### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by umarjibrilmohd** [HeliosZhao/NCDSS#10]
RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 10.76 GiB total capacity; 9.10 GiB already allocated; 101.44 MiB free; 9.35 GiB reserved in total by PyTorch)
i received this error, even when i made my batch size 2.

**Comment by umarjibrilmohd** [comment]
and im using server with enougth memory

**Comment by umarjibrilmohd** [comment]
but i works well when i run the inference but not training.

**Comment by umarjibrilmohd** [comment]
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [5,0,0], thread: [128,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [5,0,0], thread: [129,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [5,0,0], thread: [130,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "base_train.py", line 175, in <module>
    main()
  File "base_train.py", line 145, in main
    eval_train = train_base_classes(p, train_dataloader, model, criterion, optimizer, epoch,
  File "/home/mohammed/NCDSS/utils/train_utils.py", line 56, in train_base_classes
    losses.update(loss.item())
RuntimeError: CUDA error: device-side assert triggered the latest error im getting while training
